fix8-package
nalmadi/fix8 pull request #168
Opened 2024-06-30 20:14 UTC by najam-tariq

This PR attempts to address #147

- modified file paths to fit the package structure
- new way of execution:
  - make a virtual env
  - run command "pip install ."
  - enter "fix8-gui" in the terminal

TODO:
- Implement a fallback mechanism? (in case we want to support the older way of execution)

2024-07-01 22:00 UTC, nalmadi requested changes
Thank you for the excellent work, can we update the readme file in this PR as well?

2024-07-01 22:00 UTC, nalmadi commented on pyproject.toml
> +fix8-gui = "fix8.fix8:main"
Cab we make it just Fix8, please?

2024-07-01 22:15 UTC, najam-tariq commented on pyproject.toml
> +fix8-gui = "fix8.fix8:main"
Done!

2024-07-01 22:19 UTC, najam-tariq commented
> Thank you for the excellent work, can we update the readme file in this PR as well?

Done as well!

2024-07-02 15:46 UTC, nalmadi approved these changes
Just got a chance to test this on my side, and everything worked with Python 3.11

Thanks @najam-tariq!

2024-07-02 15:46 UTC, merged